Rubix982/Terrabuzz

.github/workflows/blank.yml

Fix for github actions, invalid type for 'on'

Updated blank.yml

---

client/src/App.js
client/src/components/Post/Comment.js
client/src/components/Post/PostContent.js
client/src/components/Publish/Options.js
client/src/components/Publish/PublishHeader.js
client/src/pages/post.js

Eliminating warnings and connecting everything together.

PATCH # 1, eliminate warnings

---

client/src/App.js
client/src/pages/feed.js
client/src/pages/home.js
client/src/pages/post.js
client/src/pages/profile.js
client/src/pages/publish.js
client/src/pages/search.js
client/src/pages/settings.js

🏆 Enhancements
Adds navbar to each needed page.

adding navbar to each page

---

client/src/components/Login-Register-FP/template.js
client/src/components/Login/MainContent.js
client/src/pages/ForgetPassword.js
client/src/pages/Register.js
client/src/style/Forget-Password/ForgetPassword.css
client/src/style/Login/MainContent.module.css
client/src/style/Register/Register.css

🏆 Enhancements
Just fixed some styling stuff with login, register, forget password.

MODIFIED styling with login, register, forget-password

---

client/src/components/Publish/ContentBody.js
client/src/pages/publish.js

🐛 Bug Fix
I need a cup of coffee or a good sleep, either one of each since i don't think i know what i'm doing anymore

forgot to include the styliing component, i am a DUMBO

---

client/src/components/Home/Content.js
client/src/components/Home/ContentHead.js
client/src/components/Home/Feed.js
client/src/components/Home/MainContent.js
client/src/components/Home/Post.js
client/src/components/Navbar.js
client/src/components/NavbarLoggedOut.js
client/src/pages/home.js
client/src/style/Home/Content.module.css
client/src/style/Home/ContentHead.module.css
client/src/style/Home/Feed.module.css
client/src/style/Home/MainContent.module.css
client/src/style/Home/Post.module.css
client/src/style/NavbarLoggedOut.css

🏆 Enhancements
Adds a logged out navbar, along with the homepage as well.
Forget to switch to a separate branch for the homepage. :/

SAIF naive homepage implementation for mockup

---

client/src/components/NavbarLoggedOut.js
client/src/style/NavbarLoggedOut.css

🐛 Bug Fix
NavBar.css and NavBarLoggedOut.css had the same classnames. Changed.

changing class names for navbarloggedout

---

client/src/components/Profile/MainContent.js

🐛 Bug Fix
Forgot to give arguments to navbar in profile page

forgot to give arguments to navbar in profile page

---

client/src/App.js
client/src/components/AboutUs/MainContent.js
client/src/components/Contact/MainContent.js
client/src/components/Profile/MainContent.js
client/src/components/Profile/ProfileSection.js
client/src/components/Search/InterestContent.js
client/src/components/Search/InterestProfile.js
client/src/components/Search/MainHeader.js
client/src/components/Search/Post.js
client/src/pages/AboutUs.js
client/src/pages/Contact.js
client/src/pages/search.js

🏆 Enhancements
Add `About Us` and `Contact` page.

Saif add about us contact pages

---

client/src/App.js
client/src/components/AboutUs/MainContent.js
client/src/components/Contact/MainContent.js
client/src/components/Error/MainContent.js
client/src/components/Login-Register-FP/template.js
client/src/components/Navbar.js
client/src/components/NavbarLoggedOut.js
client/src/components/NewsFeed/NewPost.js
client/src/components/Publish/PublishHeader.js
client/src/pages/AboutUs.js
client/src/pages/Contact.js
client/src/style/App.css
client/src/style/Error/MainContent.module.css
client/src/style/NavbarLoggedOut.module.css

Could not update /newPassword and /forgetPassword as they aren't refactored to the <template> component. Feedback needed if i should add <Link> to existing codebase to make it work for the time being or refactor the entire page.

Added Links in all possible pages

---

client/package.json

🏆 Enhancements
🐛 Bug Fix
🏠 Internal

vercel fix # 1

---

README.md

added images for README.md - resizing to fit

---

README.md

🏆 Enhancements
🐛 Bug Fix
🏠 Internal

added images for README.md - resizing to fit # 1

---

server/README.md

🏠 Internal
Backend file structure.

Saif backend file structure

---

.gitattributes
server/models/academics.js
server/models/connection.js
server/models/interest.js
server/models/organization.js
server/models/userInformation.js
server/package-lock.json

🏠 Internal
Basic class models for MySQL

add models for basic mysql entities

---

server/controllers/index.js
server/routes/index.js

**API endpoints calling conventions:**
indexContoller.getUserProfile (GET): localhost:5000/profile/1
indexContoller.getPost (GET): localhost:5000/post/123
indexController.searchPost (GET): localhost:5000/search-post?topic=philosophy
indexController.seachUser (GET): locahost:5000/search-user?username=john

API endpoints added with dummy contollers

---

client/src/style/Profile/ImageHeader.module.css

removing background from profile

---

server/db/mysql/ddl.sql
server/db/mysql/insertSql.sql

🏠 Internal
Just formatted and changed naming schemes.

formatted .sql files and changed the naming scheme to Snake Style

---

client/src/App.js
client/src/components/Publish/ContentBody.js
client/src/components/Publish/PublishContext.js
client/src/components/Publish/PublishHeader.js
client/src/components/Publish/TitlePlaceholder.js
client/src/services/publish.js
client/src/style/Publish/ContentBody.module.css
client/src/style/Publish/PublishHeader.module.css

🏆 Enhancements
Added the interest dropdown 

Added the interest dropdown

---

server/models/post.js

🏆 Enhancements
Just added the interest field to the Post mongoose model.

Added interests to posts' mongoose model

---

server/db/mysql/create-sql.js
server/db/mysql/ddl.sql
server/db/mysql/insert-sql.js

🐛 Bug Fix
Some problem with insertions from the DDL and the insert query. Bug noticed via docker compose logs.

fixed some syntax issues

---

client/src/components/Home/Content.js
client/src/components/Home/Post.js
client/src/services/post.js
server/services/publishPost.js

- Updated UI components
- Updated API for interest addition

/publish page hotfix 

---

client/src/components/Settings-changePassword/MainContent.js
server/controllers/index.js

🏆 Enhancements
🐛 Bug Fix
🏠 Internal

Changepassword

---

client/src/components/Settings/MainContent.js
client/src/services/settings.js

🏠 Internal
Created service for the MainContent.js

Created service for fetching information

---

client/src/components/Register/MainContent.js
client/src/services/logout.js
client/src/style/Register/register.module.css
docker-compose.dev.yaml
server/controllers/index.js
server/db/redis/connection.js
server/package-lock.json
server/package.json
server/routes/index.js
server/services/auth.js
server/services/verifyResetHash.js

🏆 Enhancements
- Added and tested server side logic for logging out
- Removed hard coded login credentials
- Added Redis to Docker Compose

Saif dynamic login pull

---

client/src/components/Login/MainContent.js
client/src/pages/feed.js
client/src/services/checkForFirstLogin.js
client/src/services/login.js
server/controllers/index.js
server/services/auth.js
server/services/firstLogin.js

Saif first login complete unit functionality

---

client/src/components/Home/Content.js
client/src/components/Home/Post.js
client/src/components/Search/InterestContent.js
client/src/components/Search/InterestProfile.js
client/src/components/Search/InterestedInEntries.js
client/src/components/Search/MainContentInterest.js
client/src/components/Search/MainContentProfile.js
client/src/components/Search/MainHeader.js
client/src/components/Search/Post.js
client/src/components/Search/PostedOnEntries.js
client/src/components/Search/SearchTypeContext.js
client/src/components/SearchBar.js
client/src/services/post.js
client/src/services/profile.js
client/src/services/search.js
server/controllers/index.js
server/models/InterestedInEntry.js
server/routes/index.js
server/services/profile.js
server/services/search.js

- all 3/3 major units implemented and issue #160 completed

Search Interest Search feature implemented

---

client/src/components/Settings/MainContent.js
client/src/services/settings.js
server/controllers/index.js
server/routes/index.js

🏆 Enhancements
🐛 Bug Fix
🏠 Internal

getSettings done

---

client/src/components/Login/MainContent.js

…credentials
🐛 Bug Fix: 
- Fixed issue #162 

issue # 162 fixed

---

client/src/components/Post/Comment.js
client/src/components/Post/CommentContent.js
client/src/components/Post/NewComment.js
server/models/CommentEntry.js
server/models/PostEntry.js
server/services/getSinglePost.js

- Integrated API to UI for comment rendering

Comments individual post

---

client/src/components/Profile/ExternalLinks.js
client/src/components/Profile/ProfileSection.js
server/controllers/index.js
server/services/profile.js

🐛 Bug Fix: 
- Profile page bug fixed, edit button will only be shown on loggedIn user profile otherwise not.

Profile page bug fixed

---

client/src/components/Navbar.js
client/src/style/Navbar.module.css
server/controllers/index.js
server/models/notification.js
server/routes/index.js

🏆 Enhancements:
- Implemented logout controller for token deletion from cookie and loggedOut removed

Logout feature enhancement

---

client/src/components/FirstLogin/MainContent.js
client/src/components/NewsFeed/NewPost.js
client/src/components/Post/PostContent.js
client/src/components/Post/PostContext.js
client/src/components/Profile/EditInfoComponent.js
client/src/components/Profile/EditProfileInformation.js
client/src/components/Register/MainContent.js
client/src/pages/post.js
client/src/pages/profile.js
client/src/services/editProfileInformation.js
client/src/services/externalLinkPost.js
client/src/style/NavbarLoggedOut.module.css
docker-compose.dev.yaml
docker-compose.yaml
server/controllers/index.js
server/db/mysql/ddl.sql
server/db/mysql/insertSql.sql
server/models/PostEntry.js
server/models/post.js
server/routes/index.js
server/services/forgetPassword.js
server/services/postExternalLinks.js
server/services/postExternalProfile.js
server/services/publishPost.js
server/services/register.js

Saif hotfix 5

---

client/src/API/API.js
client/src/components/Login/MainContent.js
client/src/components/LoginUserContext.js
client/src/components/Navbar.js
client/src/components/NewsFeed/Content.js
client/src/components/NewsFeed/FeedEntries.js
client/src/components/NewsFeed/Post.js
client/src/components/Post/CommentContent.js
client/src/components/Post/PostContent.js
client/src/components/Post/PostContext.js
client/src/components/Profile/Header.js
client/src/pages/feed.js
client/src/pages/post.js
client/src/services/login.js
server/controllers/index.js
server/models/FeedEntry.js
server/services/auth.js
server/services/feed.js
server/services/firstLogin.js
server/services/postFirstLogin.js

- implemented feed feature mapping api endpoint logic onto UI

Feed feature implemented

---

client/src/App.js
client/src/components/Home/Content.js
client/src/components/Home/Post.js
client/src/components/Navbar.js
client/src/components/NewsFeed/NewPost.js
client/src/components/NewsFeed/Post.js
client/src/components/Post/LikeToggle.js
client/src/components/Post/NewComment.js
client/src/components/Post/PostContent.js
client/src/components/Profile/Header.js
client/src/components/Search/Profile.js
client/src/components/Search/ProfileEntries.js
client/src/components/userDataContext.js
client/src/services/commentNotify.js
client/src/services/likeNotify.js
client/src/style/NewsFeed/Post.module.css
client/src/style/Post/LikeToggle.module.css
client/src/style/Post/PostContent.module.css
server/controllers/index.js
server/models/notification.js
server/routes/index.js
server/services/getNavbarInfo.js
server/services/postCommentNotification.js
server/services/postExternalProfile.js
server/services/postNotification.js
server/services/search.js

🏠 Internal
Bug fixes, finishing touches, ui modifications. See commits for explanation.

Rubix982 patch1 notificatio

---

client/src/API/API.js
client/src/App.js
client/src/components/Login/MainContent.js
client/src/components/NewsFeed/Content.js
client/src/components/Verify/MainContent.js
client/src/pages/Verify.js
client/src/services/verify.js
client/src/style/Error/MainContent.module.css
server/controllers/index.js
server/db/mongo/connection.js
server/db/mysql/sqlScript.js
server/middleware/index.js
server/routes/index.js
server/services/forgetPassword.js
server/services/register.js
server/services/template.js
server/services/verify.js

Verification feature

---

client/src/App.js
client/src/components/FirstLogin/MainContent.js
client/src/components/Login/MainContent.js
client/src/components/LoginUserContext.js
client/src/components/Navbar.js
client/src/components/Profile/ProfileContext.js
client/src/components/userDataContext.js
client/src/pages/FirstLogin.js
client/src/pages/Login.js
client/src/pages/feed.js
client/src/pages/publish.js
client/src/style/Navbar.module.css
server/routes/index.js
server/services/register.js

- Fixed redirection and fetch issues.

Redirect fix 
